### ISSUE TITLE
searching for `@` and `edt ` in switcher-plus

### ISSUE THREAD

**Issue by manogna4** [darlal/obsidian-switcher-plus#10]
I cannot search for filenames using `@` and `edt `
These are allowed characters in filenames in windows, but using these characters in switcher-plus activates the symbol navigation and editor navigation functions.
I need to resort to the native switcher to search for these files.

**Comment by darlal** [comment]
Currently if an exact match for the command is found, it immediately switches to that mode. So unfortunately, if you have filenames that _start with_ "@ " or "edt " (those exact strings) it will kick into those modes. Similarly for "@" anywhere in the search string (which is probably more likely). I'll look into this soon, thanks for the report.

**Comment by huyz** [comment]
Same here.  I have lots of notes whose title includes email addresses or twitter handles.

**Comment by Randy-Astle** [comment]
A nice feature of Quick Switcher++ is the ability to change the mode triggers. And the triggers can be more than one character.

For example, I modified all mode triggers to be a single character followed by a space. The leading character / trailing space combination is unlikely to be part of a string that I want to search for -- hasn't been yet, anyway.
Also changed the 'edt' trigger to '- ' (no single quotes, in the trigger).

**Comment by huyz** [comment]
I'm guessing that doesn't help with `@` triggering from anywhere in the search string

**Comment by Randy-Astle** [comment]
I haven't tested it since I don't have a use case for @s in a search string. (I'm also not sure why an @ embedded in the string would trigger a mode -- my understanding is that only the first character or characters are used to trigger the mode).

However, it may fix it if you are using an `@ ` (@ followed by space) character pair -- if I understand correctly, in the embedded @ scenario, the @ will always be immediately followed by non-whitespace character?

You can also change the trigger character for symbol mode to a different character or series of characters. (Until the bug is resolved if you prefer @).

**Comment by huyz** [comment]
@Randy-Astle you're right, that worked. Thanks!

**Comment by kylebradshaw** [comment]
every time I toggle "Quick Switcher ++: Open in Editor Mode" hotkey, the search field is prepended with `edt ` and I have to wipe it out before beginning my file lookup

<img width="792" alt="capture-2023-03-14-11 46 32@2x" src="https://user-images.githubusercontent.com/27273/225057729-80419b87-dc9f-4d77-b6c3-52f6aab73b44.png">

<img width="857" alt="capture-2023-03-14-11 47 54@2x" src="https://user-images.githubusercontent.com/27273/225057939-7fb453ea-accd-4974-bb69-007d91afcbc2.png">

I've tried uninstalling, reinstalling, changing hotkeys, doesn't matter. Anyone else experiencing this?
Great plugin btw! 👍

**Comment by darlal** [comment]
@kylebradshaw `edt ` is the default trigger characters for [Editor Mode](https://github.com/darlal/obsidian-switcher-plus#navigate-between-open-editors), so the `Quick Switcher ++: Open in Editor Mode` global command is just a shortcut to put the switcher into that mode. This is expected behavior, and unrelated to the issue in the thread. Please let me know if I've misunderstood the behavior you are seeing. Thanks.

**Comment by kylebradshaw** [comment]
> @kylebradshaw `edt ` is the default trigger characters for [Editor Mode](https://github.com/darlal/obsidian-switcher-plus#navigate-between-open-editors), so the `Quick Switcher ++: Open in Editor Mode` global command is just a shortcut to put the switcher into that mode. This is expected behavior, and unrelated to the issue in the thread. Please let me know if I've misunderstood the behavior you are seeing. Thanks.

I _think_ I understand. I was conflating 2 things I thought it was about opening a new file in editor mode. Got twisted up! Thanks! (coming from dendron and learning the differences) Thank you for the response
