### ISSUE TITLE
Always hide path?

### ISSUE THREAD

**Issue by csss1234** [darlal/obsidian-switcher-plus#103]
I would like to never ever see the file path, but I've tried several settings (including Preferred: Hide Path), and it still shows up for some results. For example, if I am searching for File "AAA" and type AAA, I will also see files in folder AAA, and all of them will show file path. 

Is there a way to turn it off altogether?

**Comment by darlal** [comment]
Hey @csss1234, the path is always displayed whenever it matches the search term. This is by design so you can see exactly what matched, i.e. why a result is in the result list. To illustrate this better, try this:

1. Set the Preferred path display  setting to `Hide path`
2. Create a folder named `FFF`
3. Create a file named `BBB` inside the `FFF` folder
4. In the switcher, search for `BBB`. Here you should see the `BBB`file in the result list without the path
5. Now search for `FFFBBB`. Here you should see the `BBB` file in the result list with the path, because the path matched the search term

If you really never want to see path ever, you can hide it with CSS. Open the `style.css` for the plugin, and modify `.qsp-note` to add `display: none;` like this:

`.qsp-note {
  display: none;
}`

You'll need to remember that you've done this, because the path will never be displayed and as your vault gets larger, people tend to find the path information useful.

**Comment by csss1234** [comment]
Great thank you!, I’ll try it out
