### ISSUE TITLE
No history for Navigate back/forward 

### ISSUE THREAD

**Issue by Meppo** [darlal/obsidian-switcher-plus#104]
Obdisian: v1.1.16
OS: win10 professional 1909

-----------------------

Can't navigate back to last open file after i open a file with obsidian-switcher-plus Standard mode,  unless disable the setting Override Standard mode behavior.

**Comment by darlal** [comment]
> navigate back to last open file after i open

Hey @Meppo, I'm not sure I fully understand what you're referring to. Is this regarding editor navigation, or something different? Please provide some steps to help me understand the issue better and reproduce it. Thanks!

**Comment by Meppo** [comment]
> > navigate back to last open file after i open
> 
> Hey @Meppo, I'm not sure I fully understand what you're referring to. Is this regarding editor navigation, or something different? Please provide some steps to help me understand the issue better and reproduce it. Thanks!

I use command "Navigate back/forward" to switch the files previously opened  with 'Quick Switcher'.  
but the command "Navigate back/forward"  is not working when i open files with 'Quick Switcher++: Open in standard Mode', just like no opened files history .

**Comment by darlal** [comment]
Question: do you have the Switcher++ setting [Default to open in new pane](https://github.com/darlal/obsidian-switcher-plus/tree/3.1.0#general-settings) turned on? This is the only case where I've been able to reproduce the behavior that you're describing. However, with that setting turned on, the behavior you're describing is expected, because with that setting on it will create a new tab for each file opened, and thus the new tab won't have any prior history to navigate to.

When "Override Standard mode behavior" is turned off, by default an exiting pane is reused for opening files, and so there is prior history to navigate to. If you open a file using `cmd+enter` "to open in new tab", you will again see that there is no history in this case as well.

Let me know if this is what you're seeing, because with "Default to open in new pane" turned off, history navigation seems to work as expected. Thanks!

**Comment by Meppo** [comment]
> Question: do you have the Switcher++ setting [Default to open in new pane](https://github.com/darlal/obsidian-switcher-plus/tree/3.1.0#general-settings) turned on? This is the only case where I've been able to reproduce the behavior that you're describing. However, with that setting turned on, the behavior you're describing is expected, because with that setting on it will create a new tab for each file opened, and thus the new tab won't have any prior history to navigate to.
> 
> When "Override Standard mode behavior" is turned off, by default an exiting pane is reused for opening files, and so there is prior history to navigate to. If you open a file using `cmd+enter` "to open in new tab", you will again see that there is no history in this case as well.
> 
> Let me know if this is what you're seeing, because with "Default to open in new pane" turned off, history navigation seems to work as expected. Thanks!

 Yes, history navigation seems to work as expected after  "Default to open in new pane" turned off. Thanks!  I can continue switch files with Switcher++ Now .
