### ISSUE TITLE
[Feature Request] Search by nested headings

### ISSUE THREAD

**Issue by terheyden** [darlal/obsidian-switcher-plus#105]
Let's say I have an `Animals.md` note:
```markdown
# Animals
## Cats
### Names
- Fluffy
```
And I have a `Pets.md` note:
```markdown
# Pets
## Dogs
### Names
- Fido
```
If I Quick Search for `"#names"`, I see:
- Names (in Animals)
- Names (in Pets)

Which is awesome. But I have a lot of sub-headings in my vault called `Names`, so it would be great if I could Quick Search for `"#pet names"` or `#dog name"` and see only:
```markdown
- Names (in Pets)
```

(Currently trying this yields no results.)
Thanks, this is my favorite and most-used plugin btw.

**Comment by darlal** [comment]
Thanks for the feature request! Currently the headings search does search across headings by design. There was another feature request made recently which perhaps could address this kind of workflow as well, see #97. Effectively it would enable you to do something like `#pets name` where "pet**s**" is the filename and "name" is the heading text you want to search for. The preference for the filename approach is because it is likely to yield more consistent results (better search experience overall) than trying to substring match across heading level file structure. Thoughts?
