### ISSUE TITLE
prefered file path display format has no effect

### ISSUE THREAD

**Issue by 1C0D** [darlal/obsidian-switcher-plus#122]
changing the option to full path I can see no change
I mean going from this 
![ts obsidian snippets - Mes_Notes_obsidian - Obsidian v1 3 5_2](https://github.com/darlal/obsidian-switcher-plus/assets/63018905/cf4fd340-64c6-47c6-a3f0-f692522ec9ed)
to this
![ts obsidian snippets - Mes_Notes_obsidian - Obsidian v1 3 5](https://github.com/darlal/obsidian-switcher-plus/assets/63018905/3efbf191-362f-4313-b2c0-91dc8000d65a)

**Comment by darlal** [comment]
Hey @1C0D it's hard to tell from the screenshot, are you trying to get "full path" as the display format in `Standard Mode`? if so, you may need to enable the "Override Standard mode behavior" setting as well, that will enable the multiline full path display in that mode. 

Otherwise, please provide some more details about what the behavior you're seeing, and I'm happy to help figure out what's going on. Thanks!
