### ISSUE TITLE
Autocomplete suggestions stopped working in 0.12.5?

### ISSUE THREAD

**Issue by frankreporting** [darlal/obsidian-switcher-plus#14]
Just switched to latest insider build and switcher's autocomplete is no longer working. It works with `edt` and `@` but not with default note search.

Here's the console output:

```
Uncaught TypeError: Cannot read property 'options' of undefined
    at class_1.t.getSuggestions (app.js:1)
    at class_1.t.updateSuggestions (app.js:1)
    at class_1.updateSuggestions (eval at <anonymous> (app.js:1), <anonymous>:855:52)
    at class_1.t.onInput (app.js:1)
    at class_1.onInput (eval at <anonymous> (app.js:1), <anonymous>:850:38)
t.getSuggestions @ app.js:1
t.updateSuggestions @ app.js:1
class_1.updateSuggestions @ VM115:855
t.onInput @ app.js:1
class_1.onInput @ VM115:850
```

**Comment by darlal** [comment]
This is due to some core Obsidian changes introduced in 0.12.4. Switcher++ has been updated to work with the latest version of Obsidian. Please update the plugin (to this [release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/0.0.11) using the "Check for updates" button on the "Community plugins" section of the Obsidian preferences.

**Comment by frankreporting** [comment]
Excellent. Thank you!
