### ISSUE TITLE
Bug? Prioritize recent not working

### ISSUE THREAD

**Issue by csss1234** [darlal/obsidian-switcher-plus#145]
My recents don't seem to get prioritized. I'm using the standard search

See example (Any way to get "heater" at the top of this list?):
![image](https://github.com/darlal/obsidian-switcher-plus/assets/45954264/27008128-a966-4621-9d8c-10b4d197344e)

![image](https://github.com/darlal/obsidian-switcher-plus/assets/45954264/951da274-22ad-485f-bd5a-a5c97243b807)

**Comment by darlal** [comment]
Unfortunately priority adjustment don't apply to Standard Mode. This is because standard mode is the exact core Obsidian system switcher implementation, so the match scores are not adjusted in that mode. It should behave as expected in the Heading mode, and the other custom modes. The doc should be updated to reflect this more clearly. Thanks.

**Comment by axelson** [comment]
Is it possible to create something like an "Enhanced Standard Mode" that would be like Standard Mode but it uses the match scores? One of the main reasons I want to use Obsidian Switcher++ is that I want to tweak the results in a standard-like mode.

**Comment by darlal** [comment]
Yes! [Headings Mode](https://github.com/darlal/obsidian-switcher-plus?tab=readme-ov-file#search-headings-instead-of-filename) does exactly that. And with [Release 4.1.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.1.0) you can limit searches to filenames only.

**Comment by axelson** [comment]
Great, thank you!
