### ISSUE TITLE
[Feature Request] - Filter Folders/Tags

### ISSUE THREAD

**Issue by rapatel0** [darlal/obsidian-switcher-plus#15]
My biggest gripe with the default switcher is that you cannot filter out archived things. I have a ton of old links/articles/folders that I have archived. These pollute the quick switcher and greatly diminish the functionality.

It would be great if there were a set of configurable filters to remove entries from the quick-switcher based on either folder or tag filtering

![image](https://user-images.githubusercontent.com/18704704/122498384-a4bf5e80-cfb4-11eb-9493-794b09db49ea.png)

**Comment by darlal** [comment]
Currently Switcher++ relies on the builtin switcher to perform file searches. This is a good thing because it means as the builtin search algorithm is improved or new features are added, it just works in Switcher++ too. And it enables Switcher++ to behave as a 'drop in' replacement. But it means doing things like you're suggesting is a little harder. I'll look into this, perhaps there's some not too hacky post processing or something that could be done[

**Comment by darlal** [comment]
The custom Headings Mode now allows folder based exclusions as of [this release](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.5). Check it out and I will close out this issue.

**Comment by rapatel0** [comment]
Technically, his doesn't address the specific issue of filtering from the quickswitcher, but i decided to change the default `CMD-O` toggle to headings mode. That makes this effectively fix the problem.
