### ISSUE TITLE
Fuzzy Matches Are Sometimes Ordered Above Perfect Matches

### ISSUE THREAD

**Issue by dterhorst** [darlal/obsidian-switcher-plus#162]
# Steps to Reproduce:

1. Create a new vault.
2. Turn on community plugins.
3. Install the Quick Switcher++ community plugin.
4. Enable the Quick Switcher++ community plugin.
5. Add the following notes and aliases:
  * Talia Dawnseeker, the Fictional Furry Character from Neewhere
    * aliases: Talia Dawnseeker
  * Talia Dawnseeker Looking at the Camera, the AI Clip by Luma Dream Machine
    * aliases: Talia Dawnseeker Looking at the Camera
  * Talia Dawnseeker Looking at the Camera, the One-Image Lora for Pony Diffusion V6 XL
    * aliases: Talia Dawnseeker Looking at the Camera
  * Talia Dawnseeker Profile Shot, the AI Image by Midjourney
    * aliases: Talia Dawnseeker Profile Shot
6. Invoke the "Quick Switcher++: Open in Standard Mode" command.
7. Type "Talia Dawnseeker Lora".

# Expected Result:

I would expect the perfect match to be ordered above the partial fuzzy matches:

![expected](https://github.com/darlal/obsidian-switcher-plus/assets/100437146/c9ccee99-c014-4b44-9713-417c6c1c014c)

# Actual Result:

The partial fuzzy matches are ordered above the perfect match:

![actual](https://github.com/darlal/obsidian-switcher-plus/assets/100437146/cc50c9a9-1ab3-4e9e-8bf2-591a773a8b4c)

# Notes:

Obsidian v1.6.5
Quick Switcher++ v4.2.2

I presume that the fuzzy matches were prioritized higher because the characters that matched appeared earlier in the title. However, I would argue that this is less useful than giving the user the result that most closely matches their query, if one exists.

**Comment by darlal** [comment]
Switcher++ currently uses the Obsidian builtin fuzzy search algorithm, if you try this same experiment with the builtin Obsidian quick switcher, you'll see the same behavior. As such, this is not something that Switcher++ will change in the near term. You could open a feature request in the Obsidian forum to have the builtin behavior change.

As an aside, I think the score in the "perfect match" case is going to be lower than the score for the cases, because a) the perfect match case matches over a much longer string, and b) as you mentioned, the matches are found much later in the string.
