### ISSUE TITLE
[Feature Request] Allow switching to inline aliases defined with Dataview

### ISSUE THREAD

**Issue by atkirtland** [darlal/obsidian-switcher-plus#169]
Hi, thanks for the plugin. This is a speculative feature request since I'm not sure how feasible it is. A [couple](https://forum.obsidian.md/t/show-inline-aliases-in-quickswitcher/35963) [people](https://github.com/blacksmithgu/obsidian-dataview/issues/915) in 2022 had the same thought I have now, namely that it would be nice to be able to define aliases inline rather than only in the YAML frontmatter. They both received quick rejections to the notion because of a fundamental way core Obsidian handles aliases; they are of a separate class from fields defined inline. I'm curious if it would be possible for an extended switcher to bypass this and allow switching to notes based on inline-defined aliases. This would apply to the standard mode of the plugin.

**Comment by darlal** [comment]
Hey there! As far as I'm aware, Aliases are treated differently than other file metadata, which may be part of the reason that the Dataview issue you referenced was closed not implemented. I think the core of the problem is that while you could call the inline property "Aliases", the behavior would be quite different from core Obsidian defined Aliases. And although some sort of quick-switcher functionality could be build to support navigating via these inline fields, all the other standard Alias capability would be absent - and likely quite confusing for users. 

It's probably? feasible to develop a new plugin that syncs and manages some sort of "linking" behavior between inline fields and Aliases though. Something like that is well beyond the scope of switcher++ for the time being.
