### ISSUE TITLE
Upgrade from Starred to Bookmarks

### ISSUE THREAD

**Issue by JaspalSuri** [darlal/obsidian-switcher-plus#172]
Hi,

QuickSwitcher++ is amazing. 

Can you upgrade the plugin to reference the bookmarks file (perhaps on top of the starred file)?

**Comment by darlal** [comment]
Hi there! 

I think you may be referring to the old "Starred" files core Obsidian functionality that was migrated to the "Bookmarks" core Obsidian plugin functionality. QuickSwitcher++ also [migrated](https://github.com/darlal/obsidian-switcher-plus/releases/tag/3.2.0) to use the Bookmarks functionality a while ago. 

I'd recommend updating QuickSwitcher++ to the latest [release](https://github.com/darlal/obsidian-switcher-plus/releases) to use the Bookmarks functionality. But please let me know if I've misunderstood your question, thanks!

**Comment by JaspalSuri** [comment]
Hi Darlal, thank you for responding.

I have the latest version of the plugin. I think the issue is that if the Starred file remains then QS++ still refers to it, because I see the starred notes in the search results.

I will delete the file and see if that helps.

**Comment by darlal** [comment]
I might be misunderstanding what you're describing. You referencing the old "Starred" plugin is confusing because Obsidian doesn't support that plugin anymore. There's now a new "Bookmarks" plugin, but IIRC Obsidian migrates your old starred items to the new Bookmarks. So maybe that's what you are seeing?

Alternatively, please take a look at issue #174 which was just fixed, does that solve the issue?

If not, please provide the exact steps to recreate the problem so I can look into it more. Thanks!
