### ISSUE TITLE
Option to disable quick selection hotkeys

### ISSUE THREAD

**Issue by itsonlyjames** [darlal/obsidian-switcher-plus#179]
~In referencee to https://github.com/darlal/obsidian-switcher-plus/issues/124, is there an option to disable this?~

~It conflicts with [my plugin](https://github.com/itsonlyjames/obsidian-quick-select/) that attaches quick select hotkeys to __all__ modals and prompt windows (not a promotion).~

Update: there is an option to disable this which I found in https://github.com/darlal/obsidian-switcher-plus/commit/7199325b208da7effa7ef1efe7b509c73583ef7c, however it doesn't show up in the settings. It requires manual adjustment in `settings.json`. This is this issues focus now.

**Comment by darlal** [comment]
Hey there!

I wasn't aware of the obsidian-quick-select plugin, thanks for sharing. Yes, the Switcher++ settings.json can be edited directly to change a lot of behaviors, including this one, that's intentional. 

It looks like obsidian-quick-select indiscriminately injects its functionality into .suggestion-item elements that's not a group. I imagine there may be other plugins with this kind of functionality already built in natively like Switcher++ does. So perhaps a more durable approach would be for obsidian-quick-select to have an "exclusion list". The exclusion list could be used to prevent obsidian-quick-select from injecting its custom functionality into other plugins that already support this behavior natively.

**Comment by frankreporting** [comment]
+1 for this feature request. I use symbols for certain notes, i.e. ¶ for reference notes. These symbols require the `option` key for fast typing, so the new quick selection hotkeys interfere with my regular typing and workflow. I'll look into the manual overrides in `settings.json` but it would be nice to have a built-in solution.

**Comment by itsonlyjames** [comment]
Is it intentional to forego the setting in the UI?

It indsicriminately injects functionality so as to affect **all** modals, including suggestion prompts. So it works with tag selectors, search prompts, workspace modals, etc. Rather than targetting each of these plugins (whether internal or not), it simply applies a global approach, future proofing the functionality. 
I'm unaware of any other plugins that natively implement quick select functionality. I also don't think an exclusion is necessary given switcher++ uses opt+number to select, whereas quick select uses cmd+number (least on mac), so *technically* they can exist together with no issues. 
I wouldn't however want to have cmd+number usage everywhere _except_ this plugin, that would not be beneficial to the effiency the plugin creates. 
Hence, this issue, which sought a UI setting to disable the selection hotkeys.

**Comment by domodwyer** [comment]
A confusing edge case: on a British keyboard on mac laptops, inserting the `#` symbol requires an `option+3` [key combination](https://www.apple.com/uk/shop/product/MK2A3B/A/magic-keyboard-british-english). 

This triggers the "open the third file" behaviour, instead of inserting the `#` so I can't search by headers!

**Comment by darlal** [comment]
@domodwyer oh interesting! Thanks for sharing. 

Release [4.6.1](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.6.1) introduces a UI toggle in the General Setting to disable the Quick Open hotkeys in Switcher++ directly. Optionally, the Quick Open hotkeys are also externalized to the plugins `data.json` file so they can be changed there directly too.

**Comment by darlal** [comment]
>Is it intentional to forego the setting in the UI?

It was. There are many behavior toggles that provide flexibility in the rare cases when they are needed, but are used so infrequently that the benefit of creating UIs for them does not outweigh the added complexity and maintenance burden.

>it simply applies a global approach, future proofing the functionality.

Yea, I understand the intent here. As far as I can tell (admittedly, I didn't look too deeply) obsidian-quick-select is either "globally on" or "globally off". My suggestion was to highlight that there are bound to be cases (this is one example) where obsidian-quick-select users could benefit from some flexibility between those two extremes. In the same way that you're requesting some flexibility from Switcher++ here. An "exclusion list" is just one way to provide that flexibility, but there are other ways too (and perhaps I shouldn't have jumped directly into solutioning, sorry for that).

Anyhow, release [4.6.1](https://github.com/darlal/obsidian-switcher-plus/releases/tag/4.6.1) introduces a UI toggle in the General Setting to disable this behavior in Switcher++ directly. Thanks!

**Comment by domodwyer** [comment]
Thanks for the speedy change @darlal! Appreciate the work building Switcher++

**Comment by frankreporting** [comment]
Thank you!
