### ISSUE TITLE
[Feature Request] Search headings through all files

### ISSUE THREAD

**Issue by mrjackphil** [darlal/obsidian-switcher-plus#22]
Currently, we can search headings only after file selection. 
Might be useful to discover headings as it works in an Obsidian Publish search.

![image](https://user-images.githubusercontent.com/16895902/125161147-58b5a300-e189-11eb-9017-e0f42d410fad.png)

**Comment by darlal** [comment]
@mrjackphil adding support for headings is something I've been considering, please see the [discussion](https://github.com/darlal/obsidian-switcher-plus/discussions/20) I head started on the topic. 

I don't use Obsidian Publish, so I'm not familiar with how it works. The screenshot you posted looks more like a general "search" box rather than the QuickSwitcher. I'd be interested in hearing how you'd like to see this feature work. Let's continue the conversation in the [discussion](https://github.com/darlal/obsidian-switcher-plus/discussions/20) thread instead. Thanks!

**Comment by darlal** [comment]
@mrjackphil this functionality is now live with release [1.0.2](https://github.com/darlal/obsidian-switcher-plus/releases/tag/1.0.2). Check it out. 

I will close this issue out. Thanks.
