### ISSUE TITLE
confuse where to use it?

### ISSUE THREAD

**Issue by realliyifei** [darlal/obsidian-switcher-plus#34]
Should it be used in the switcher and type # then trigger the search of headers? On my side nothing happens.

demo:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/32441766/153035666-f6617f06-7c07-48c3-bc81-a9a7de25624c.png">

setting:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/32441766/153035674-93b43710-1f63-4a4f-89c4-02cda23a3c05.png">

**Comment by darlal** [comment]
@realliyifei looks like you may still be using the builtin switcher. Once you have the plugin installed and enabled, you have to trigger Switcher++ instead of the regular builtin switcher. You can trigger the Switcher++ by 1) using the command palette, or, 2) using a hotkey

**Using the command palette**

1. Bring up the obsidian command palette
2. Search for `switcher++`
3. Click on any of the `Quick Switcher++: Open` commands
<img width="702" alt="image" src="https://user-images.githubusercontent.com/5191776/153070738-c94ea9e8-30de-4159-b40e-efd6cbeb4e7d.png">

**Using a hotkey**

1. Assign one or more of the Switcher++ [custom commands](https://github.com/darlal/obsidian-switcher-plus#global-commands-for-hotkeys) to a hotkey. 
2. Trigger Switcher++ using the configured hotkey

**Comment by realliyifei** [comment]
thanks; i misunderstood it since i thought it expands the functions on the switcher directly

**Comment by darlal** [comment]
Oh it does. All the functionality that exists in the core switcher works in Switcher++ too. But you still have to trigger it separately. Most people just un-assign the builtin switcher hotkey, and re-assign it to switcher++ you don't lose any functionality.
