### ISSUE TITLE
indenting in symbol mode

### ISSUE THREAD

**Issue by manogna4** [darlal/obsidian-switcher-plus#5]
It would be great to have indentation in the symbol mode.

I see that you have H1, H2 etc marked, and that is certainly useful, but indentation would make the hierarchy very obvious and allow fast navigation of a large note too.

This functionality kind of replaces the outline.

Congratulations on the plug-in btw. This is the only plug in I have installed even though plug-ins are still in alpha.

**Comment by darlal** [comment]
Thanks for the comment. This is something I gave some thought to initially and ultimately decided against. The main issue is that indentation is only useful when there is surrounding context, in the form of related items above, and items below. When the surrounding related items are not visible then the indentation loses its meaning. 

The indentation works well in the outline view because all the surrounding items are always visible. So indentation helps you see how they relate to each other.  In the quick switcher however, as soon as you start to filter the list you will likely end up with a disparate list of unrelated items that appear to be arbitrarily intended relative to each other. So indentation just looks weird and doesn't provide any value.

**Comment by manogna4** [comment]
I agree that indentation makes more sense with context. As one starts typing and this context disappears, I can see why indentation would start to lose appeal.

Maybe one way would be to preserve the hierarchy above a symbol in the modal but make the non relevant parts inactive, so that the context of the relevant symbol is still visible. But I guess that's not easy

Also, I'd argue that it may still be useful even without the context. Right now you have 'H2', 'H3' and lower header levels labelled accordingly even if the corresponding 'H1' (or higher headers) vanishes . The loss of context occurs here too as you start typing, and yet you see the benefit in giving header level information. Indenting would just be a way of physically representing the header level instead just using a text qualifier.

Secondly, could just scroll through the 'find symbol' modal to treat it like an outline, but with a lot more functionality.

**Comment by darlal** [comment]
I think showing the header indentation when there is no filter text makes the most sense, giving you the equivalent of the outline view. One thing to note, is that headers (at a minimum) and other symbol types would have to be grouped together for this to work, because there is currently no metadata available for indentation (parent heading) for things like links, tags, ect.. I'll look into implementing this soon.

**Comment by manogna4** [comment]
agreed. Looking forward to that implementation.

In vscode `@` shows symbols by occurrence and `@:` shows symbols grouped by type. This is just something to think about. It makes sense for code, but is probably not as useful for notes

**Comment by manogna4** [comment]
> It makes sense for code, but is probably not as useful for notes

I have been thinking about this. While it may not make sense for all header levels, it definitely makes sense for the H2s. (I use H1, just once per file - I saw it as a recommended convention somewhere).

**Comment by darlal** [comment]
Yea typically there's only 1 H1. For grouping by type, I would think all headers grouped together and indented would be more useful than all H2s as a flat list.

**Comment by darlal** [comment]
Might want to hit that "Update" button 😄 

<img width="720" alt="image" src="https://user-images.githubusercontent.com/5191776/103696776-f0cd9800-4f6c-11eb-9569-5c72ae79ec3e.png">

I pushed an update that exposes a new setting for this. When enabled, symbols are shown by occurrence, indented under the nearest #header.

**Comment by manogna4** [comment]
excellent! functional and aesthetic! 
I would like the option to turn off showing links. I have a note with lots of links and it clutters up the structure. This way the add-in will function like a keyboard friendly outline navigator.

![image](https://user-images.githubusercontent.com/16304061/103970185-a9722200-518d-11eb-930d-46a57c88296d.png)

**Comment by darlal** [comment]
Glad you like it 🙂 

Thanks for the feedback on additional customization. I will close this issue, and create a separate one for the follow up customization idea. Thanks!

**Comment by manogna4** [comment]
great.

For now, I have commented out the line `push(symbolData.links, SymbolType.Link);` so that links are not generated in the plug-in. Seems to work fine for now.
