### ISSUE TITLE
Feature request: sort order

### ISSUE THREAD

**Issue by esm7** [darlal/obsidian-switcher-plus#53]
Hey,
Quick Switcher++ is awesome, there's just one major thing that I'm missing from it: a sort order that can prioritize recently open files and modified time.
For me, and I assume also for most other users, newer and recently-opened notes have a considerably higher chance of being the most relevant match for a given query. The fact Obsidian's internal switcher and Quick Switcher++ ignore this metric, and just match plain text, is missing a huge opportunity to provide much better results!
Thanks in advance :)

**Comment by darlal** [comment]
Thanks for this feature request. I will give it some thought.

**Comment by darlal** [comment]
Release [2.3.7](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.3.7) introduces the [Result priority adjustments](https://github.com/darlal/obsidian-switcher-plus#general-settings) setting that can be used to prioritize certain result types so that they appear higher/lower in the result list. Thanks!
