### ISSUE TITLE
[bug report] Symbol list mode show symbols in the previous file, not current file

### ISSUE THREAD

**Issue by woshitoutouge** [darlal/obsidian-switcher-plus#61]
when i open the plugin and press @ in file B, i expected it show headings and links in file B, but it show headings and links in file A (last opened file)
OB version: 0.15.3
quick swither ++ version: 1.0.12
![image](https://user-images.githubusercontent.com/99337435/177031388-9d7d568f-f6d7-477c-a032-4a891852097a.png)

**Comment by darlal** [comment]
Hey @woshitoutouge This is because when the trigger character `@` is typed, it acts upon the suggestion that is currently selected (highlighted) in the result list. As can be seen in the screenshot you posted the suggestion `A heading 2` is selected (highlighted). So this behavior is expected.

To get what I think you are looking for, the symbol list for the active file, there are two options.

1. Trigger the switcher open using the `Quick Switcher++: Open in Symbol Mode` command. This will auto-activate symbol mode for the active file. I think this is what you may be looking for.
2. Type some filter text to have the target file `fileB` show up in the result list, selected it, then type `@`. This will trigger symbol mode for `fileB`. The screenshot is effectively showing this case.

**Comment by woshitoutouge** [comment]
@darlal option 1 works perfect for me! And I totally misunderstand what symbol mode is, and it's more powerful than i thought! 😂 you're very kind, thanks a lot!
