### ISSUE TITLE
"Only parent folder" option not working

### ISSUE THREAD

**Issue by frankreporting** [darlal/obsidian-switcher-plus#62]
I'm not sure I understand what this new option is supposed to do. No matter which option I select, the suggester shows the files exactly the same: full path. I tried "only parent folder" thinking it would be like `folder/filename` even if, say, that file is 3 folders deep. Instead, every option displays files the same way: `folder-level-1/folder-level-2/filename` etc.

Maybe I'm just misunderstanding what that option controls?

**Comment by darlal** [comment]
Hi @frankreporting, the `Preferred file path display format` option only applies to the customs modes: `editor`, `headings`, and `starred`. It does not apply to the default, Obsidian built-in `standard` mode. Here's a screenshot of what `Parent folder & filename` in `headings` mode should look like. Please let me know if the setting is not having an effect on the custom modes. Thanks.

![image](https://user-images.githubusercontent.com/5191776/177672252-4fe1f2f3-c02e-4643-a779-0f83b645e43b.png)

**Comment by frankreporting** [comment]
Oh that makes sense! Do you have plans to support the feature in standard mode? I love that cleaner display!

**Comment by darlal** [comment]
Switcher++ is designed to be a "drop-in" replacement for the build-in system switcher, it tries really hard to not modify the build-in system functionality, so probably not. However, if you are really interested in filename searches, `headings` mode does have an option to also show filename suggestions alongside the heading suggestions - and those, I am planning to apply this option to as well.

**Comment by yutaizhou** [comment]
Hi! I would just like to bump the OP's feature request. 

I use the plugin almost exclusively in standard mode, and my project folders often have deep nesting, with files often having overlapping substring in their names. (e.g. "Meeting Project1", "Meeting Project2", folder file with same name as the folder, etc). This just isn't visually pleasing if my search query is only "meeting". In this case, showing only the file itself or the file with parent folder would help greatly. 

I know this plugin is meant to be a drop-in replacement for the default quickswitcher, but I think at least having the option to turn on display formats in standard mode would be great. Otherwise, the only visually pleasing way of picking out the file I want would be to style it with Supercharged Links or similar plugins.

**Comment by darlal** [comment]
Hey @yutaizhou first, thank you for putting in the extra effort to find this exiting (Closed) issue, instead of just blindly creating a brand new duplicate issue. I really appreciate it 🙂

> I use the plugin almost exclusively in standard mode

Question: have you considered/tried using `headings` mode with the [Search filenames](https://github.com/darlal/obsidian-switcher-plus#search-headings-configuration)  setting enabled? This setting will allow you to search filenames just like `standard` alongside headings. Additionally, to minimize the heading results even more, you could also disable the [Search all headings](https://github.com/darlal/obsidian-switcher-plus#search-headings-configuration) setting. This would allow you to get filename results with the path display formats support.

**Comment by yutaizhou** [comment]
Hi @darlal, I understand that pain of duplicate issues all too well to inflict it upon another haha!

As for your suggestion, it actually works great! Only downside is that it's not as snappy as standard mode (i.e. suggestions don't update with each new character I type), which is really a fundamental limit of searching for all headings. 

I guess the only way to overcome that is to disable searching for headings, but at that point, might as well as apply the display format preference to standard mode 😅

**Comment by darlal** [comment]
@yutaizhou I'm glad the alternative is working for now. I'll give this some thought, it has come up several times already since the new path display format feature was introduced. Thanks!

**Comment by darlal** [comment]
@yutaizhou @frankreporting FYI.. with [release 2.3.0](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.3.0) the custom functionality is now supported in `Standard` mode too.

**Comment by frankreporting** [comment]
I saw that! Thanks for incorporating that suggestion!

**Comment by yutaizhou** [comment]
That's awesome! Glad to have the speed of standard mode back in my default search :D
