### ISSUE TITLE
Possible Bug: Ctrl + P Doesn't Open Popover in Windows

### ISSUE THREAD

**Issue by julroger2013** [darlal/obsidian-switcher-plus#84]
I use both a Windows machine and a MacBook with Obsidian. When using Switcher ++, the search box modal (regardless of mode - editor, standard, etc) indicates at the bottom that cmd + P (Mac) or ctrl + P (Windows) should open a popover view of the currently selected search result. 

On the MacBook, this functions exactly as I would expect, opening a hover editor instance. But on Windows it instead scrolls through the search results, moving up by one result each time (as if I had pressed the "up" arrow key). 

Any idea why this might be happening? I wouldn't be shocked if it's some sort of user error 😬

By the way, the new separation of filename & path in Standard Mode is 😍🔥 Makes searching for files about 1000x easier without having to read my (very deeply nested) sets of filepaths.

**Comment by darlal** [comment]
Hey @julroger2013 `ctrl+p` and `ctrl+n` are well established shortcuts for navigating previous/next in lists, Switcher++ [supports](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/switcherPlus/switcherPlusKeymap.ts#L131) this convention, and registers those shortcuts.

Hover Editor [registers the shortcuts](https://github.com/nothingislost/obsidian-hover-editor/blob/master/src/main.ts#L172) `cmd+p` on Mac and `ctrl+p` on windows to open in new popover. So on Mac it works fine, but on Windows the `ctrl+p` conflicts because it's already registered for navigation. I would recommend you open an issue on the Hover Editor repo to raise this to the authors. Perhaps Hover Editor switching to`win+p` or `alt+p` key on Windows could be an option.

**Comment by julroger2013** [comment]
Oh that's very interest, and makes total sense. So the text-based prompt (e.g. esc to dismiss) at the bottom of the Switcher ++ Modal is not displaying shortcuts you designated specifically for Switcher ++? 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/94991208/201530823-3aa89121-44cd-4b07-9013-c8b6194909db.png">

I'll put an issue in the Hover Editor repo. Thank you! And yes -- the new updates made Switcher ++ even more outstanding than it already was.

**Comment by darlal** [comment]
The text-based prompt instructions at the bottom of the switcher (and custom key bindings) can come from a variety of sources. There are ones that I design specifically for Switcher++ like `cmd+o` to open in new window, there are some built in Obsidian ones like `cmd+enter` to open in new tab, and other plugins can "inject" their own custom functionality as well like HoverPopup with `cmd+p` to open in new popover. This flexibility is actually a good thing, but sometimes you end up with conflicts like this one.

**Comment by julroger2013** [comment]
You're awesome. Just, really awesome. Thank you for explaining.
