### ISSUE TITLE
Canvan files are not listed

### ISSUE THREAD

**Issue by Cutuchiqueno** [darlal/obsidian-switcher-plus#92]
Is it possible that canvas files introduced in Obsidian 1.1 are not included in Quick Switcher Plus search of files? Obsidian default switcher, links and embeds make it possible to search for these files as well and I think this is a reasonable decision. I would like to propose that for Quick Switcher Plus as well.

**Comment by darlal** [comment]
Hey @Cutuchiqueno canvas files may or may be searchable in the switcher depending on your settings configuration. The "Show Attachments" setting in the system switcher settings is the one that toggles the ability to search for canvas files. With that setting enable canvas files should show up alongside other results, with that setting disabled, canvas files won't be searched at all (they'll never appear in the results list). Let me know if this answers your question, thanks!

**Comment by Cutuchiqueno** [comment]
thanks for your explanations! I did not come about this. The reason why, would be an argument I would like to make for consideration. More precisely, I did not consider a canvas an attachment. And I think there are reasons for it that could be generalized from my mistake. I think, attachments are resources that primarily are supposed to "live in the note" and not on their own while canvas are more of a note themselves (or even something bigger thant that), only organized around another layout principle. From this follows, that the way you use canvas and the situations in which you work with them are very different from attachments.

Having all this said, of cause, I agree that it is much more consistent to follow the logic that Obsidian applies and that you described below.

**Comment by KraXen72** [comment]
+1, i would like quick switcher plus to treat canvas files as notes (optional setting) thanks

**Comment by KraXen72** [comment]
@darlal hi, is it possible to show canvas files in "quick swicher plus plus" while 1) not showing any other attachments (i don't care about quick-switching to images) and 2) not having the core quick switcher plugin enabled (why have 2 quick switcher plugins enabled at the same time??)
  
preferably, just add a toggle in this plugin's settings to also include `.canvas` files with a `canvas` tag, like they are in the sidebar:  
![image](https://user-images.githubusercontent.com/21956756/210459888-331f1fbc-e7da-4bf4-929b-59cfc48ac1b2.png)

thanks a lot!!

**Comment by KraXen72** [comment]
could this be implemented? it's quite annoying not being able to switch to canvas files.. thanks!

**Comment by mayankguptadotcom** [comment]
Thank you so much for this plugin! It's so much better than the core plugin.

IMO, Canvas is not an attachment as suggested by @KraXen72 as well. They are documents that Obsidian understands, images, PDFs are not native to Obsidian and should be considered as attachments.

It'll be good to have Quick Switcher++ to find Canvas documents.

**Comment by darlal** [comment]
Seems like there's some interest in this. It's curious that the Obsidian devs themselves implemented this behind the attachment setting. I can see the argument that it's a content type that Obsidian understand, and native to the app.

Adding an override setting in Switcher++ could be done, however it would only work for custom modes. It would not apply to the `Standard` mode, because `Standard` mode is the builtin, out of the box, Obsidian quick switcher implementation. So if having this in custom mode is good enough, then I'm happy to add it.

**Comment by KraXen72** [comment]
what does custom mode mean exactly in the context of this plugin?

**Comment by darlal** [comment]
@KraXen72 the different search modes that QSP provides, e.g [Headings mode](https://github.com/darlal/obsidian-switcher-plus#search-headings-instead-of-filename), [Symbole mode](https://github.com/darlal/obsidian-switcher-plus#symbol-navigation-headings-hashtags-links-embeddings), [Editor mode](https://github.com/darlal/obsidian-switcher-plus#navigate-between-open-editors), etc..

**Comment by KraXen72** [comment]
hmm, if i understand correctly, i would have to use some if the prefixes to switch to canvas files? and if i just opened the quickswitcher++ by default and typed, it would not show canvas files?

if this is the case, that's really not ideal. i think it would be a good idea to instead require users to "show attachements" but add a filename filter as to which file types get included or excluded (option to toggle the input/textarea from whitelist to blacklist) - this way, id enable "show attachements" and only whitelist "canvas files" (i do not care about quickly switching to an image)

the plugin "another quick switcher" uses a very similar approach, so you could use it's code as a reference. and no, i do not want to use "another quick switcher" instead of this, this plugin has many more useful features.

hope it's doable & good luck!

**Comment by darlal** [comment]
The global command `Quick Switcher++: Open` which you likely have mapped to a hotkey triggers the builtin Obsidian switcher functionality `Standard` mode (with some primarily cosmetic QSP tweaks).

The global command `Quick Switcher++: Open in Headings Mode` which can also be mapped to a hotkey, triggers custom _superset functionality_ `Headings mode`, this mode can also search filenames just like `Standard` mode, and more. So in my initial suggestion, you could map your hotkey to this mode instead, and everything would work like today, plus you'd get canvas files (once the new setting is implemented). You wouldn't have to worry about switching modes (prefixes) because you'd just use the same hotkey you use today.

The allow/exclude list suggestion is a good one and could easily be implemented in the custom modes. But it would be harder to implement in `Standard` mode because that would require somehow modifying/overriding how the builtin Obsidian switcher deals with files.

Anyway, I'll give this some more thought and look into the feasibility of extending this FR to `Standard` mode, but an initial implementation will likely only cover custom modes to start with.

**Comment by KraXen72** [comment]
okay, thank you. i think it should be possible to filter out whitelist/blacklisted attachments with a simple array.filter pass, but i am not sure how exactly the base quick switcher works and how much stuff you can inject into it from a plugin's context.

**Comment by darlal** [comment]
Release [2.3.8](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.3.8) introduces a file extension override setting for `headings mode` with canvas listed by default.
